// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jdplus/main/ws/v1/toolkit_basic.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace JDPlus.Main.WS.V1 {

  /// <summary>Holder for reflection information generated from jdplus/main/ws/v1/toolkit_basic.proto</summary>
  public static partial class ToolkitBasicReflection {

    #region Descriptor
    /// <summary>File descriptor for jdplus/main/ws/v1/toolkit_basic.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ToolkitBasicReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVqZHBsdXMvbWFpbi93cy92MS90b29sa2l0X2Jhc2ljLnByb3RvEhFqZHBs",
            "dXMubWFpbi53cy52MRooamRwbHVzL21haW4vd3MvdjEvdG9vbGtpdF9tZXNz",
            "YWdlcy5wcm90bzKsDQoLVHNGdW5jdGlvbnMSTAoKR2V0VmVyc2lvbhIbLmpk",
            "cGx1cy5tYWluLndzLnYxLkVtcHR5RHRvGiEuamRwbHVzLm1haW4ud3MudjEu",
            "VmVyc2lvbkluZm9EdG8SWgoJTm9ybWFsaXplEiUuamRwbHVzLm1haW4ud3Mu",
            "djEuVHNGdW5jdGlvbklucHV0RHRvGiYuamRwbHVzLm1haW4ud3MudjEuVHNG",
            "dW5jdGlvbk91dHB1dER0bxJkCg9Ob3JtYWxpemVTdHJlYW0SJS5qZHBsdXMu",
            "bWFpbi53cy52MS5Uc0Z1bmN0aW9uSW5wdXREdG8aJi5qZHBsdXMubWFpbi53",
            "cy52MS5Uc0Z1bmN0aW9uT3V0cHV0RHRvKAEwARJgCgpTdGF0aXN0aWNzEiUu",
            "amRwbHVzLm1haW4ud3MudjEuVHNGdW5jdGlvbklucHV0RHRvGisuamRwbHVz",
            "Lm1haW4ud3MudjEuRGVzY3JpcHRpdmVTdGF0aXN0aWNzRHRvEmoKEFN0YXRp",
            "c3RpY3NTdHJlYW0SJS5qZHBsdXMubWFpbi53cy52MS5Uc0Z1bmN0aW9uSW5w",
            "dXREdG8aKy5qZHBsdXMubWFpbi53cy52MS5EZXNjcmlwdGl2ZVN0YXRpc3Rp",
            "Y3NEdG8oATABEk0KA1BjdBIeLmpkcGx1cy5tYWluLndzLnYxLlBjdElucHV0",
            "RHRvGiYuamRwbHVzLm1haW4ud3MudjEuVHNGdW5jdGlvbk91dHB1dER0bxJX",
            "CglQY3RTdHJlYW0SHi5qZHBsdXMubWFpbi53cy52MS5QY3RJbnB1dER0bxom",
            "LmpkcGx1cy5tYWluLndzLnYxLlRzRnVuY3Rpb25PdXRwdXREdG8oATABElEK",
            "BURlbHRhEiAuamRwbHVzLm1haW4ud3MudjEuRGVsdGFJbnB1dER0bxomLmpk",
            "cGx1cy5tYWluLndzLnYxLlRzRnVuY3Rpb25PdXRwdXREdG8SWwoLRGVsdGFT",
            "dHJlYW0SIC5qZHBsdXMubWFpbi53cy52MS5EZWx0YUlucHV0RHRvGiYuamRw",
            "bHVzLm1haW4ud3MudjEuVHNGdW5jdGlvbk91dHB1dER0bygBMAESWwoJQWdn",
            "cmVnYXRlEiYuamRwbHVzLm1haW4ud3MudjEuQWdncmVnYXRpb25JbnB1dER0",
            "bxomLmpkcGx1cy5tYWluLndzLnYxLlRzRnVuY3Rpb25PdXRwdXREdG8SZQoP",
            "QWdncmVnYXRlU3RyZWFtEiYuamRwbHVzLm1haW4ud3MudjEuQWdncmVnYXRp",
            "b25JbnB1dER0bxomLmpkcGx1cy5tYWluLndzLnYxLlRzRnVuY3Rpb25PdXRw",
            "dXREdG8oATABEmoKD0hvZHJpY2tQcmVzY290dBIqLmpkcGx1cy5tYWluLndz",
            "LnYxLkhvZHJpY2tQcmVzY290dElucHV0RHRvGisuamRwbHVzLm1haW4ud3Mu",
            "djEuSG9kcmlja1ByZXNjb3R0T3V0cHV0RHRvEnQKFUhvZHJpY2tQcmVzY290",
            "dFN0cmVhbRIqLmpkcGx1cy5tYWluLndzLnYxLkhvZHJpY2tQcmVzY290dElu",
            "cHV0RHRvGisuamRwbHVzLm1haW4ud3MudjEuSG9kcmlja1ByZXNjb3R0T3V0",
            "cHV0RHRvKAEwARJdCgtCdWlsZFRzRGF0YRImLmpkcGx1cy5tYWluLndzLnYx",
            "LkJ1aWxkVHNEYXRhSW5wdXREdG8aJi5qZHBsdXMubWFpbi53cy52MS5Uc0Z1",
            "bmN0aW9uT3V0cHV0RHRvEmcKEUJ1aWxkVHNEYXRhU3RyZWFtEiYuamRwbHVz",
            "Lm1haW4ud3MudjEuQnVpbGRUc0RhdGFJbnB1dER0bxomLmpkcGx1cy5tYWlu",
            "LndzLnYxLlRzRnVuY3Rpb25PdXRwdXREdG8oATABEm0KEEJ1aWxkVHNEYXRh",
            "VGFibGUSKy5qZHBsdXMubWFpbi53cy52MS5CdWlsZFRzRGF0YVRhYmxlSW5w",
            "dXREdG8aLC5qZHBsdXMubWFpbi53cy52MS5CdWlsZFRzRGF0YVRhYmxlT3V0",
            "cHV0RHRvEokBCh1Qcm9jZXNzVGVtcG9yYWxEaXNhZ2dyZWdhdGlvbhIzLmpk",
            "cGx1cy5tYWluLndzLnYxLlRlbXBvcmFsRGlzYWdncmVnYXRpb25SZXF1ZXN0",
            "RHRvGjMuamRwbHVzLm1haW4ud3MudjEuVGVtcG9yYWxEaXNhZ2dyZWdhdGlv",
            "blJlc3VsdHNEdG9CJwoRamRwbHVzLm1haW4ud3MudjGqAhFKRFBsdXMuTWFp",
            "bi5XUy5WMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::JDPlus.Main.WS.V1.ToolkitMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
