// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: jdplus/main/ws/v1/toolkit_basic.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace JDPlus.Main.WS.V1 {
  public static partial class TsFunctions
  {
    static readonly string __ServiceName = "jdplus.main.ws.v1.TsFunctions";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.EmptyDto> __Marshaller_jdplus_main_ws_v1_EmptyDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.EmptyDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.VersionInfoDto> __Marshaller_jdplus_main_ws_v1_VersionInfoDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.VersionInfoDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.TsFunctionInputDto> __Marshaller_jdplus_main_ws_v1_TsFunctionInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.TsFunctionInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.TsFunctionOutputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> __Marshaller_jdplus_main_ws_v1_DescriptiveStatisticsDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.PctInputDto> __Marshaller_jdplus_main_ws_v1_PctInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.PctInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.DeltaInputDto> __Marshaller_jdplus_main_ws_v1_DeltaInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.DeltaInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.AggregationInputDto> __Marshaller_jdplus_main_ws_v1_AggregationInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.AggregationInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto> __Marshaller_jdplus_main_ws_v1_HodrickPrescottInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.HodrickPrescottInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> __Marshaller_jdplus_main_ws_v1_HodrickPrescottOutputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.BuildTsDataInputDto> __Marshaller_jdplus_main_ws_v1_BuildTsDataInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.BuildTsDataInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto> __Marshaller_jdplus_main_ws_v1_BuildTsDataTableInputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto> __Marshaller_jdplus_main_ws_v1_BuildTsDataTableOutputDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto> __Marshaller_jdplus_main_ws_v1_TemporalDisaggregationRequestDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto> __Marshaller_jdplus_main_ws_v1_TemporalDisaggregationResultsDto = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.EmptyDto, global::JDPlus.Main.WS.V1.VersionInfoDto> __Method_GetVersion = new grpc::Method<global::JDPlus.Main.WS.V1.EmptyDto, global::JDPlus.Main.WS.V1.VersionInfoDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVersion",
        __Marshaller_jdplus_main_ws_v1_EmptyDto,
        __Marshaller_jdplus_main_ws_v1_VersionInfoDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_Normalize = new grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Normalize",
        __Marshaller_jdplus_main_ws_v1_TsFunctionInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_NormalizeStream = new grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "NormalizeStream",
        __Marshaller_jdplus_main_ws_v1_TsFunctionInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> __Method_Statistics = new grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Statistics",
        __Marshaller_jdplus_main_ws_v1_TsFunctionInputDto,
        __Marshaller_jdplus_main_ws_v1_DescriptiveStatisticsDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> __Method_StatisticsStream = new grpc::Method<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "StatisticsStream",
        __Marshaller_jdplus_main_ws_v1_TsFunctionInputDto,
        __Marshaller_jdplus_main_ws_v1_DescriptiveStatisticsDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_Pct = new grpc::Method<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Pct",
        __Marshaller_jdplus_main_ws_v1_PctInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_PctStream = new grpc::Method<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "PctStream",
        __Marshaller_jdplus_main_ws_v1_PctInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_Delta = new grpc::Method<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delta",
        __Marshaller_jdplus_main_ws_v1_DeltaInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_DeltaStream = new grpc::Method<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "DeltaStream",
        __Marshaller_jdplus_main_ws_v1_DeltaInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_Aggregate = new grpc::Method<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Aggregate",
        __Marshaller_jdplus_main_ws_v1_AggregationInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_AggregateStream = new grpc::Method<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "AggregateStream",
        __Marshaller_jdplus_main_ws_v1_AggregationInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> __Method_HodrickPrescott = new grpc::Method<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HodrickPrescott",
        __Marshaller_jdplus_main_ws_v1_HodrickPrescottInputDto,
        __Marshaller_jdplus_main_ws_v1_HodrickPrescottOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> __Method_HodrickPrescottStream = new grpc::Method<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "HodrickPrescottStream",
        __Marshaller_jdplus_main_ws_v1_HodrickPrescottInputDto,
        __Marshaller_jdplus_main_ws_v1_HodrickPrescottOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_BuildTsData = new grpc::Method<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BuildTsData",
        __Marshaller_jdplus_main_ws_v1_BuildTsDataInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> __Method_BuildTsDataStream = new grpc::Method<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "BuildTsDataStream",
        __Marshaller_jdplus_main_ws_v1_BuildTsDataInputDto,
        __Marshaller_jdplus_main_ws_v1_TsFunctionOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto, global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto> __Method_BuildTsDataTable = new grpc::Method<global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto, global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "BuildTsDataTable",
        __Marshaller_jdplus_main_ws_v1_BuildTsDataTableInputDto,
        __Marshaller_jdplus_main_ws_v1_BuildTsDataTableOutputDto);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto, global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto> __Method_ProcessTemporalDisaggregation = new grpc::Method<global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto, global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ProcessTemporalDisaggregation",
        __Marshaller_jdplus_main_ws_v1_TemporalDisaggregationRequestDto,
        __Marshaller_jdplus_main_ws_v1_TemporalDisaggregationResultsDto);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::JDPlus.Main.WS.V1.ToolkitBasicReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TsFunctions</summary>
    [grpc::BindServiceMethod(typeof(TsFunctions), "BindService")]
    public abstract partial class TsFunctionsBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.VersionInfoDto> GetVersion(global::JDPlus.Main.WS.V1.EmptyDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Compute (y-mean(y))/stdev(y) 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> Normalize(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task NormalizeStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.TsFunctionInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Basic descriptive statistics 
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> Statistics(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StatisticsStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.TsFunctionInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> Pct(global::JDPlus.Main.WS.V1.PctInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task PctStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.PctInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> Delta(global::JDPlus.Main.WS.V1.DeltaInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task DeltaStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.DeltaInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> Aggregate(global::JDPlus.Main.WS.V1.AggregationInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task AggregateStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.AggregationInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> HodrickPrescott(global::JDPlus.Main.WS.V1.HodrickPrescottInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task HodrickPrescottStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> BuildTsData(global::JDPlus.Main.WS.V1.BuildTsDataInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task BuildTsDataStream(grpc::IAsyncStreamReader<global::JDPlus.Main.WS.V1.BuildTsDataInputDto> requestStream, grpc::IServerStreamWriter<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto> BuildTsDataTable(global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto> ProcessTemporalDisaggregation(global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TsFunctions</summary>
    public partial class TsFunctionsClient : grpc::ClientBase<TsFunctionsClient>
    {
      /// <summary>Creates a new client for TsFunctions</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TsFunctionsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TsFunctions that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public TsFunctionsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TsFunctionsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected TsFunctionsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.VersionInfoDto GetVersion(global::JDPlus.Main.WS.V1.EmptyDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVersion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.VersionInfoDto GetVersion(global::JDPlus.Main.WS.V1.EmptyDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.VersionInfoDto> GetVersionAsync(global::JDPlus.Main.WS.V1.EmptyDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVersionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.VersionInfoDto> GetVersionAsync(global::JDPlus.Main.WS.V1.EmptyDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVersion, null, options, request);
      }
      /// <summary>
      /// Compute (y-mean(y))/stdev(y) 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Normalize(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Normalize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Compute (y-mean(y))/stdev(y) 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Normalize(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Normalize, null, options, request);
      }
      /// <summary>
      /// Compute (y-mean(y))/stdev(y) 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> NormalizeAsync(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NormalizeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Compute (y-mean(y))/stdev(y) 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> NormalizeAsync(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Normalize, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> NormalizeStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return NormalizeStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> NormalizeStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_NormalizeStream, null, options);
      }
      /// <summary>
      /// Basic descriptive statistics 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto Statistics(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Statistics(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Basic descriptive statistics 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto Statistics(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Statistics, null, options, request);
      }
      /// <summary>
      /// Basic descriptive statistics 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> StatisticsAsync(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StatisticsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Basic descriptive statistics 
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> StatisticsAsync(global::JDPlus.Main.WS.V1.TsFunctionInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Statistics, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> StatisticsStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StatisticsStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto> StatisticsStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_StatisticsStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Pct(global::JDPlus.Main.WS.V1.PctInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Pct(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Pct(global::JDPlus.Main.WS.V1.PctInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Pct, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> PctAsync(global::JDPlus.Main.WS.V1.PctInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PctAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> PctAsync(global::JDPlus.Main.WS.V1.PctInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Pct, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> PctStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PctStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> PctStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_PctStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Delta(global::JDPlus.Main.WS.V1.DeltaInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delta(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Delta(global::JDPlus.Main.WS.V1.DeltaInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> DeltaAsync(global::JDPlus.Main.WS.V1.DeltaInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeltaAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> DeltaAsync(global::JDPlus.Main.WS.V1.DeltaInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delta, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> DeltaStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeltaStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> DeltaStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_DeltaStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Aggregate(global::JDPlus.Main.WS.V1.AggregationInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Aggregate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto Aggregate(global::JDPlus.Main.WS.V1.AggregationInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Aggregate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> AggregateAsync(global::JDPlus.Main.WS.V1.AggregationInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AggregateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> AggregateAsync(global::JDPlus.Main.WS.V1.AggregationInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Aggregate, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> AggregateStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AggregateStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> AggregateStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_AggregateStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto HodrickPrescott(global::JDPlus.Main.WS.V1.HodrickPrescottInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HodrickPrescott(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto HodrickPrescott(global::JDPlus.Main.WS.V1.HodrickPrescottInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_HodrickPrescott, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> HodrickPrescottAsync(global::JDPlus.Main.WS.V1.HodrickPrescottInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HodrickPrescottAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> HodrickPrescottAsync(global::JDPlus.Main.WS.V1.HodrickPrescottInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_HodrickPrescott, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> HodrickPrescottStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return HodrickPrescottStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto> HodrickPrescottStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_HodrickPrescottStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto BuildTsData(global::JDPlus.Main.WS.V1.BuildTsDataInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildTsData(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TsFunctionOutputDto BuildTsData(global::JDPlus.Main.WS.V1.BuildTsDataInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BuildTsData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> BuildTsDataAsync(global::JDPlus.Main.WS.V1.BuildTsDataInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildTsDataAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TsFunctionOutputDto> BuildTsDataAsync(global::JDPlus.Main.WS.V1.BuildTsDataInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BuildTsData, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> BuildTsDataStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildTsDataStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncDuplexStreamingCall<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto> BuildTsDataStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_BuildTsDataStream, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto BuildTsDataTable(global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildTsDataTable(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto BuildTsDataTable(global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_BuildTsDataTable, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto> BuildTsDataTableAsync(global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuildTsDataTableAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto> BuildTsDataTableAsync(global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_BuildTsDataTable, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto ProcessTemporalDisaggregation(global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ProcessTemporalDisaggregation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto ProcessTemporalDisaggregation(global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ProcessTemporalDisaggregation, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto> ProcessTemporalDisaggregationAsync(global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ProcessTemporalDisaggregationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto> ProcessTemporalDisaggregationAsync(global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ProcessTemporalDisaggregation, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override TsFunctionsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TsFunctionsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(TsFunctionsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetVersion, serviceImpl.GetVersion)
          .AddMethod(__Method_Normalize, serviceImpl.Normalize)
          .AddMethod(__Method_NormalizeStream, serviceImpl.NormalizeStream)
          .AddMethod(__Method_Statistics, serviceImpl.Statistics)
          .AddMethod(__Method_StatisticsStream, serviceImpl.StatisticsStream)
          .AddMethod(__Method_Pct, serviceImpl.Pct)
          .AddMethod(__Method_PctStream, serviceImpl.PctStream)
          .AddMethod(__Method_Delta, serviceImpl.Delta)
          .AddMethod(__Method_DeltaStream, serviceImpl.DeltaStream)
          .AddMethod(__Method_Aggregate, serviceImpl.Aggregate)
          .AddMethod(__Method_AggregateStream, serviceImpl.AggregateStream)
          .AddMethod(__Method_HodrickPrescott, serviceImpl.HodrickPrescott)
          .AddMethod(__Method_HodrickPrescottStream, serviceImpl.HodrickPrescottStream)
          .AddMethod(__Method_BuildTsData, serviceImpl.BuildTsData)
          .AddMethod(__Method_BuildTsDataStream, serviceImpl.BuildTsDataStream)
          .AddMethod(__Method_BuildTsDataTable, serviceImpl.BuildTsDataTable)
          .AddMethod(__Method_ProcessTemporalDisaggregation, serviceImpl.ProcessTemporalDisaggregation).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TsFunctionsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetVersion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.EmptyDto, global::JDPlus.Main.WS.V1.VersionInfoDto>(serviceImpl.GetVersion));
      serviceBinder.AddMethod(__Method_Normalize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.Normalize));
      serviceBinder.AddMethod(__Method_NormalizeStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.NormalizeStream));
      serviceBinder.AddMethod(__Method_Statistics, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto>(serviceImpl.Statistics));
      serviceBinder.AddMethod(__Method_StatisticsStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.TsFunctionInputDto, global::JDPlus.Main.WS.V1.DescriptiveStatisticsDto>(serviceImpl.StatisticsStream));
      serviceBinder.AddMethod(__Method_Pct, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.Pct));
      serviceBinder.AddMethod(__Method_PctStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.PctInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.PctStream));
      serviceBinder.AddMethod(__Method_Delta, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.Delta));
      serviceBinder.AddMethod(__Method_DeltaStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.DeltaInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.DeltaStream));
      serviceBinder.AddMethod(__Method_Aggregate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.Aggregate));
      serviceBinder.AddMethod(__Method_AggregateStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.AggregationInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.AggregateStream));
      serviceBinder.AddMethod(__Method_HodrickPrescott, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto>(serviceImpl.HodrickPrescott));
      serviceBinder.AddMethod(__Method_HodrickPrescottStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.HodrickPrescottInputDto, global::JDPlus.Main.WS.V1.HodrickPrescottOutputDto>(serviceImpl.HodrickPrescottStream));
      serviceBinder.AddMethod(__Method_BuildTsData, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.BuildTsData));
      serviceBinder.AddMethod(__Method_BuildTsDataStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::JDPlus.Main.WS.V1.BuildTsDataInputDto, global::JDPlus.Main.WS.V1.TsFunctionOutputDto>(serviceImpl.BuildTsDataStream));
      serviceBinder.AddMethod(__Method_BuildTsDataTable, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.BuildTsDataTableInputDto, global::JDPlus.Main.WS.V1.BuildTsDataTableOutputDto>(serviceImpl.BuildTsDataTable));
      serviceBinder.AddMethod(__Method_ProcessTemporalDisaggregation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::JDPlus.Main.WS.V1.TemporalDisaggregationRequestDto, global::JDPlus.Main.WS.V1.TemporalDisaggregationResultsDto>(serviceImpl.ProcessTemporalDisaggregation));
    }

  }
}
#endregion
